modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="GNU LGPLv3"
issueTrackerURL="https://github.com/Darkorg69/bettermaterials" #optional
[[mods]] #mandatory
modId="bettermaterials" #mandatory
version="1.16.5-1.1.0" #mandatory
displayName="Better Materials" #mandatory
#updateJSONURL="" #optional
displayURL="https://github.com/Darkorg69/bettermaterials" #optional
logoFile="bettermaterials.png" #optional
credits="Thanks for this mod goes to Java." #optional
authors="Darkorg" #optional
description='''A minecraft mod, expanding upon vanilla resources, making them more useful and realistic.'''

[[dependencies.bettermaterials]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.bettermaterials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
