modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="GNU LGPLv3"
issueTrackerURL="https://github.com/Darkorg69/BetterMaterials/issues" #optional

[[mods]] #mandatory
modId="bettermaterials" #mandatory
version="1.1.0-1.18.2" #mandatory
displayName="Better Materials" #mandatory
#updateJSONURL="" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/bettermaterials" #optional
logoFile="bettermaterials.png" #optional
credits="Thanks for this mod goes to Java and the Forge team." #optional
# A text field displayed in the mod UI
authors="Darkorg" #optional
description='''A minecraft mod, expanding upon the vanilla game, making materials more useful and realistic.'''

[[dependencies.bettermaterials]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.bettermaterials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
